title: Kyle Stellmann
remote_theme: PaulLeCam/millennial-jekyll-theme
url: "https://KyleStellmann.github.io"
baseurl: "/Portfolio"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
