
disqus:
  comments: false
  disqus_shortname: ''
google-ID: ''

menu:
- {name: 'Engineering Projects',  url: 'projects'}
- {name: 'About Me',              url: 'about'}
- {name: 'Contact Me',            url: 'contact'}

social:

- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kyle-stellmann-b65b78380'}
- {icon: 'envelope', link: 'mailto: stellm98@rowan.edu'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

